#!/usr/bin/env python3
"""Generate src/mod/fh1_symbols.inc, the mod symbol table (NP-7.2).

Reads config/mod/fh1-symbols.toml (semantic symbols and offsets) and every
[[midasm_hook]] of config/rexglue/analysis/main-xex.toml (as hook.<name>),
and writes a sorted C++ table. With --check, fails when the checked-in file
differs from what would be generated.
"""
from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SYMBOLS = ROOT / "config" / "mod" / "fh1-symbols.toml"
HOOKS = ROOT / "config" / "rexglue" / "analysis" / "main-xex.toml"
OUTPUT = ROOT / "src" / "mod" / "fh1_symbols.inc"


def generate() -> str:
    symbols = tomllib.loads(SYMBOLS.read_text(encoding="utf-8"))
    hooks = tomllib.loads(HOOKS.read_text(encoding="utf-8")).get("midasm_hook", [])
    entries: dict[str, int] = {}
    for name, address in symbols["symbols"].items():
        entries[name] = int(address)
    for hook in hooks:
        name = "hook." + hook["name"]
        if name in entries and entries[name] != int(hook["address"]):
            raise ValueError(f"{name} has two addresses")
        entries[name] = int(hook["address"])
    lines = [
        "// Generated by tools/generate-fh1-symbols.py from config/mod/fh1-symbols.toml",
        "// and config/rexglue/analysis/main-xex.toml. Do not edit.",
        f'// Executable: {symbols["executable"]} {symbols["sha256"]}',
        "",
        "PINYON_SYMBOL_EXECUTABLE(\"%s\", \"%s\")" % (symbols["executable"], symbols["sha256"]),
    ]
    for name in sorted(entries):
        lines.append(f'PINYON_SYMBOL("{name}", 0x{entries[name]:08X})')
    for name in sorted(symbols["offsets"]):
        lines.append(f'PINYON_OFFSET("{name}", {int(symbols["offsets"][name])})')
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = generate()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT.relative_to(ROOT)} is out of date; run tools/generate-fh1-symbols.py")
            return 1
        print("symbol table is up to date")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
